/**
 * One document as the repository returns it: FLAT, with the uploader's public
 * fields joined in — the rule `PostRow`, `CommentRow` and `EventRow` all
 * follow. The nesting into `{ uploader: { ... } }` happens in the view mapper,
 * so the shape the wire sees is decided in exactly one place.
 *
 * `communityId` IS present. The delivery route resolves a document by id and
 * must then check it against the slug in the URL — a question about ids, not
 * names — and the view mapper drops it explicitly rather than leaving it to be
 * stripped downstream.
 */
export interface DocumentRow {
  id: string;
  communityId: string;
  name: string;
  contentType: string;
  byteSize: number;
  createdAt: Date;
  uploaderHandle: string;
  uploaderDisplayName: string;
}

export interface DocumentRepositoryPort {
  create(input: {
    /**
     * Generated by the CALLER, not left to the column default — the bytes
     * have to land in the bucket under this id BEFORE the row that makes the
     * id discoverable exists. `MediaRepositoryPort.create` records the same
     * requirement and what it costs to get wrong: a row whose bytes are still
     * being written is a row a reader can already ask for.
     */
    id: string;
    communityId: string;
    uploaderId: string;
    name: string;
    contentType: string;
    byteSize: number;
  }): Promise<DocumentRow>;
  /**
   * Newest first — a library reads most-recent-first, like the feed and unlike
   * a comment thread. Excludes soft-deleted rows.
   *
   * UNPAGINATED, and deliberately: a community's library is bounded by what an
   * owner has bothered to upload, not by what every member can write. If that
   * stops being true it grows a keyset cursor like the feed's.
   */
  listByCommunity(communityId: string): Promise<DocumentRow[]>;
  /**
   * One document by id, for the delivery and delete paths.
   *
   * `null` when the id has never existed OR when the row is soft-deleted —
   * both are absence to every caller, and the two causes collapse into the
   * same 404 exactly as `PostRepositoryPort.getById` records.
   */
  findById(id: string): Promise<DocumentRow | null>;
  /** Idempotent: deleting an already-deleted document is a no-op, not an error. */
  softDelete(id: string): Promise<void>;
}
